# Change these first
owner: kaustubhk24 # Your GitHub organization or username, where this repository lives
repo: status.myapms.com # The name of this repository

sites:
  - name: Developer Site
    url: https://dev.myapms.com
  - name: Documentation Site
    url: https://docs.myapms.com
  - name: Instance 81946
    url: https://dev81946.service-now.com/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.myapms.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: APMS Status
  introTitle: Status Page
  introMessage: Status
  navbar:
    - title: Status
      href: /
    - title: Docs
      href: https://docs.myapms.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
